{
 "title": "Solar Power (Prometheus)",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Current Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg without (kubernetes_node, instance) (solar_w_now{meter=\"consumption\"})",
     "legendFormat": "{{meter}}"
    }
   ]
  },
  {
   "title": "Trees Saved",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "🌲" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without (kubernetes_node, instance) (solar_wh_lifetime_total{meter=\"production\"}/1000/55.3)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Production",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg without (kubernetes_node, instance) (solar_w_now{meter=\"production\"})",
     "legendFormat": "{{meter}}"
    }
   ]
  },
  {
   "title": "Today's Consumed Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without (kubernetes_node, instance) (solar_wh_today{meter=\"consumption\"}/1000*0.1456)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Today's Produced Savings",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without (kubernetes_node, instance) (solar_wh_today{meter=\"production\"}/1000*0.1456)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumed Today",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without (kubernetes_node, instance) (solar_wh_today{meter=\"consumption\"})",
     "legendFormat": "{{meter}}"
    }
   ]
  },
  {
   "title": "Consumed Lifetime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without (kubernetes_node, instance) (solar_wh_lifetime_total{meter=\"consumption\"})",
     "legendFormat": "{{meter}}"
    }
   ]
  },
  {
   "title": "Produced Today",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without (kubernetes_node, instance) (solar_wh_today{meter=\"production\"})",
     "legendFormat": "{{meter}}"
    }
   ]
  },
  {
   "title": "Produced Lifetime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without (kubernetes_node, instance) (solar_wh_lifetime_total{meter=\"production\"})",
     "legendFormat": "{{meter}}"
    }
   ]
  },
  {
   "title": "Lifetime Consumed Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without (kubernetes_node, instance) (solar_wh_lifetime_total{meter=\"consumption\"}/1000*0.1456)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lifetime Produced Savings",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg without (kubernetes_node, instance) (solar_wh_lifetime_total{meter=\"production\"}/1000*0.1456)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Energy Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "avg without (kubernetes_node, instance) (solar_w_now{meter=\"production\"})",
     "legendFormat": "Produced"
    },
    {
     "expr": "avg without (kubernetes_node, instance) (solar_w_now{meter=\"consumption\"})",
     "legendFormat": "Consumed"
    },
    {
     "expr": "sum((avg without (kubernetes_node, instance) (solar_w_now{meter=\"consumption\"}) - ignoring (meter) (avg without (kubernetes_node, instance) (solar_w_now{meter=\"production\"}))) >= 0 or on() vector(0))",
     "legendFormat": "Imported"
    },
    {
     "expr": "sum((avg without(kubernetes_node, instance) (solar_w_now{meter=\"production\"}) - ignoring (meter) (avg without(kubernetes_node, instance) (solar_w_now{meter=\"consumption\"}))) >= 0 or on() vector(0))",
     "legendFormat": "Exported"
    }
   ]
  }
 ]
}